[back](./02-network-mining.ipynb)

---
## `Python Matrix Mining`

There are quite a few popular libraries to perform matrix operations like *matrix multiplication*, *transpose* etc in Python.

Here, we will be looking at the below two libraries

- **Numpy**
- **Pandas**

### `Numpy`

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

In [3]:
print(A)
print(type(A)) # ndarray -> N dimensional array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
# Transpose a matrix
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
# Dot product of two matrices
np.dot(A, B.T) # Transposing B because, in matrix multiplication, the number of rows in one matrix should be the number of columns on the second matrix

array([[ 50,  68],
       [122, 167]])

In [6]:
# Create a new matrix with every element powered by 2
C = A**2
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
# Create a new matrix D by subtracting 1 from each element in matrix A
D = A-1
D

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
# Retrieving the diagonal elements of a matrix
D.diagonal() # Since D is a 2x3 matrix, the diagonal will be two elements

array([0, 4])

In [9]:
# We can actually use the numpy matrix property to convert a 2D array into a matrix
A = np.matrix(A)
B = np.matrix(B)
C = np.matrix(C)
D = np.matrix(D)

In [10]:
print(A) # there is no visual difference, but the type of A previously was ndarray, and now it's matrix
print(type(A))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [11]:
print(A)
# Return the indices of the elements that are non-zero
A.nonzero()

[[1 2 3]
 [4 5 6]]


(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [12]:
# Difference between two matrices
A-B

matrix([[-6, -6, -6],
        [-6, -6, -6]])

In [13]:
# Sum of two matrices
A+B

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [14]:
# Dot product of two matrices
A.dot(B.T)

matrix([[ 50,  68],
        [122, 167]])

In [15]:
# Sum and Mean of all the elements in a matrix
print('Matrix A:\n{}'.format(A))
print('Sum of matrix A: {}'.format(A.sum()))
print('Mean of matrix A: {}'.format(A.mean()))

Matrix A:
[[1 2 3]
 [4 5 6]]
Sum of matrix A: 21
Mean of matrix A: 3.5


### `Pandas`

In [16]:
import pandas as pd

In [17]:
A_df = pd.DataFrame(A)
A_df

0  1  2
0  1  2  3
1  4  5  6

In [18]:
type(A_df)

pandas.core.frame.DataFrame

### `Conclusion`


---
[next](./04-sql-mining.ipynb)